### ISSUE TITLE
Use React.cache

### ISSUE THREAD

**Issue by HaNdTriX** [jherr/next13-use-warning#2]
Hey @jherr I just saw your video and was wondering why you are not using React.cache?

```ts
"use client";
import { use, cache } from "react";

const fetchData = cache(async () => {
  const res = await fetch("http://localhost:3000/api/pokemon");
  return res.json();
});

export default function Home() {
  const pokemon = use(fetchData());
  return <pre>{JSON.stringify(pokemon, null, 2)}</pre>;
}
```

Afaik this takes care of deduping the call and allows you to pass params to your `fetchData` function. 

Normally I use this stuff on the server to dedupe promises that are not related to next-fetch.

**Comment by jherr** [comment]
it didn't exist at the time the video was filmed.
